name: Development Deploy

on:
  push: 
    branches: ["*"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run dev-teste
      # - run: npm run test
      # - run: npm run build
      # - run: npm run deploy